---
- name: "Run a {{ container_name }} container with default parameters"
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: true
    restart_policy: "{{ restart_if }}"
    pull: true
    image: "{{ image_name }}:{{ image_tag }}"
    exposed_ports:
      - "{{ exposed_port1 }}:{{ exposed_port1 }}"
      - "{{ exposed_port2 }}:{{ exposed_port2 }}"
    published_ports:
      - "{{ exposed_port1 }}:{{ exposed_port1 }}"
      - "{{ exposed_port2 }}:{{ exposed_port2 }}"
    env:
      USER: "{{ def_user }}"
      PASSWORD: "{{ def_password }}"
  when: not mount_volumes
  tags: 3proxy

- name: "Run a {{ container_name }} container with external configuration"
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: true
    restart_policy: "{{ restart_if }}"
    pull: true
    image: "{{ image_name }}:{{ image_tag }}"
    exposed_ports:
      - "{{ exposed_port1 }}:{{ exposed_port1 }}"
      - "{{ exposed_port2 }}:{{ exposed_port2 }}"
    published_ports:
      - "{{ exposed_port1 }}:{{ exposed_port1 }}"
      - "{{ exposed_port2 }}:{{ exposed_port2 }}"
    volumes:
      - "{{ cfg_volume }}"
      - "{{ log_volume }}"
  when: mount_volumes
  tags: 3proxy
