---
- name: Debug
  debug: var="mount_volumes"
  tags: 3proxy

- name: Run a 3proxy-telegram container with default parameters
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: true
    restart_policy: "{{ restart_if }}"
    pull: true
    image: "{{ image_name }}:{{ image_tag }}"
    published_ports:
      - "{{ exposed_port_int }}:{{ exposed_port_ext }}"
    env:
      USER: "{{ def_user }}"
      PASSWORD: "{{ def_password }}"
  when: not mount_volumes
  tags: 3proxy

- name: Run a 3proxy-telegram container with external configuration
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: true
    restart_policy: "{{ restart_if }}"
    pull: true
    image: "{{ image_name }}:{{ image_tag }}"
    published_ports:
      - "{{ exposed_port_int }}:{{ exposed_port_ext }}"
    volumes:
      - "{{ cfg_volume }}"
      - "{{ log_volume }}"
  when: mount_volumes
  tags: 3proxy
